server:
  port: 8020

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user
          predicates:
            - Path=/api/user/**
            - Method=GET
          uri: lb://ms-use

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

springdoc:
  enable-native-support: true
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /MS-USER/v3/api-docs
        name: User Service
      - url: /MS-ACCOUNT/v3/api-docs
        name: Payment Service
